var server=require("./server.js");
var router=require("./router.js");
var requestHandlers=require("./requestHandlers.js");
var Gdate=new require("./GDate.js");
var date=new Gdate();
var topmain=require("../TOPMAIN.js");
global.date=date;
var time=0;
global.time=time;
setInterval(function() {
   topmain.walkerManager();
   console.log(date.getFullDate());
   //console.log(time);
   date.time++;
},1700);
var handle={};
handle['/']=requestHandlers.start;
handle['/start']=requestHandlers.start;
handle['/upload']=requestHandlers.upload;
handle['/register']=requestHandlers.register;
handle['/login']=requestHandlers.login;
handle['/111111']=requestHandlers.imba;
handle["/me"]=requestHandlers.me;
handle["/get"]=requestHandlers.get;
handle["/create"]=requestHandlers.create;
handle["/getI"]=requestHandlers.getInfo;
handle["/getNpc"]=requestHandlers.getNF;
handle["/time"]=requestHandlers.Time;
server.start(router.route,handle);
