/*quests.register(new Quest("Найди бэйджик", ["square","square"] , 0, false, [50, 0, 0, 20], null));
quests.register(new Quest("Найди Софью Григорьевну и иди в корпус купи печенья]", ["random", "mainHouse"] , 0, false, [40, -5, 5, 10], null));
quests.register(new Quest("Иди в магазин и возвращайся в корпус", ["shop", "mainHouse"] , 0, false, [50, -10, 10, 20], null));
quests.register(new Quest("Найди бэйджик", ["random", "random"] , 0, false, [50, 0, 0, 20], /*бейджик*/null));
quests.register(new Quest("Найди Софью Григорьевну и иди в корпус, купи печенья", ["random", "mainHouse"] , 0, false, [40, -5, 5, 10], null));
quests.register(new Quest("Сходи на завтрак", ["canteen"], 0, false, [30, 0, 20, 5], null));
quests.register(new Quest("Сходи на обед", ["canteen"], 0, false, [50, 0, 25, 5], null));
quests.register(new Quest("Сходи на полдник", ["canteen"], 0, false, [30, 0, 10, 5], null));
quests.register(new Quest("Сходи на ужин", ["canteen"], 0, false, [50, 0, 20, 5], null));
quests.register(new Quest("Сходи на второй ужин", ["canteen"], 0, false, [50, 0, 10, 5], null));
quests.register(new Quest("Найди Татьяну Ивановну и возьми бейджик", ["random", "mainHouse"], 0, false, [20, 0, 0, -20], null));
quests.register(new Quest("Переоденься и пойди на футбольное поле, поиграй в футбол", ["mainHouse", "soccer"], 0, false, [30, 0, 10, 15/*случайное число*/], null));
quests.register(new Quest("Иди в корпус и ложись спать", ["mainHouse"], 0, false, [20, 0, 30, 30], null));
quests.register(new Quest("Выйди на зарядку", ["soccer"], 0, false, [30, 0, 10, 30], null));
quests.register(new Quest("Пропусти зарядку", ["mainHouse"], 0, false, [30, 0, 10, -30], null));
quests.register(new Quest("Выйди на линейку раньше Татьяны Ивановны", ["square"], 0, false, [20, 0, 0, 20], null));
quests.register(new Quest("Пропусти линейку", ["mainHouse"], 0, false, [20, 0, 0, -20], null));
quests.register(new Quest("Успей в мастерскую до начала занятий", ["workshops"], 0, false, [20, 0, 0, 20], null));
quests.register(new Quest("Опоздай в мастерскую", ["workshops"], 0, false, [20, 0, 0, -20], null));
quests.register(new Quest("Успей на лекцию", ["canteen"], 0, false, [40, 0, 0, 20], null));
quests.register(new Quest("Пропусти лекцию", ["mainHouse"], 0, false, [40, 0, 0, -20], null));
quests.register(new Quest("Прочти задачу дня и реши её", ["mainHouse", "random"], 0, false, [50, 20, 0, 40], /*бейджик*/ null));
quests.register(new Quest(/*Если встретил Татьяну Ивановну*/"Поздоровайся с Татьяной Ивановной", ["random"], 0, false, [10, 0, 0, 30], null));
quests.register(new Quest("Возьми фотографии в мастерской и отнеси их в бильярдную", ["workshops", "pool"], 0, false, [40, 0, 0, 30], null));
quests.register(new Quest(/*Если здоровье меньше определенного значения*/"Отправляйся в мед. пункт", ["mainHouse"], 0, false, [20, 0, 80,0 /*случайное число*/], null));
quests.register(new Quest("Приберись в своей комнате", ["mainHouse"], 0, false, [20, 0, 0, 10], null));
quests.register(new Quest("Сходи на фильм", ["canteen"], 0, false, [20, 0, 0, 10], null));
quests.register(new Quest("Отнеси стулья из мастерской в столовую", ["workshops", "canteen"], 0, false, [50, 0, 0, 30], null));
quests.register(new Quest("Займись перепродажей вещей из магазина: сходи в магазин и продай купленые вещи в корпусе",["shop", "mainHouse"], 0, false,[50, 20, 0, 20], null));//есть шанс, что кто-то заподозрит неладное, в следствие чего мораль уменьшится
quests.register(new Quest("Придумай шутку для КВН", ["random"], 0, false, [20, 0, 0, 10/*случайное число*/], null));
quests.register(new Quest("Помоги накрыть в столовой", ["canteen"], 0, false, [20, 0, 0, 15], null));
quests.register(new Quest("Поменяй свое постельное белье", ["mainHouse"], 0, false, [20, 0, 0, 15], null));
quests.register(new Quest("Сходи в душ", ["mainHouse"], 0, false, [20, 0, 0, 10], null));
quests.register(new Quest("Позвонить родителям", ["random"], 0, false, [20, 0, 0, 5], null));
quests.register(new Quest("Погладить кота", ["random"], 0, false, [40, 0, 0, 40], null));
quests.register(new Quest("Встреть родственников у ворот", ["gate"], 0, false, [20, 0, 20, 5], null));
*/